### ISSUE TITLE
There has been a critical error on your website

### ISSUE THREAD

**Issue by uhthing** [strangerstudios/pmpro-constant-contact#12]
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.3
Current theme: Astra (version 1.8.7)
Current plugin: Paid Memberships Pro - Constant Contact Add On (version 1.0.2)
PHP version 7.2.24

Error Details
=============
An error of type E_ERROR was caused in line 622 of the file /srv/htdocs/wp-content/plugins/pmpro-constant-contact/pmpro-constant-contact.php. Error message: Uncaught Error: Call to undefined method Ctct\ConstantContact::getLists() in /srv/htdocs/wp-content/plugins/pmpro-constant-contact/pmpro-constant-contact.php:622
Stack trace:
#0 /wordpress/core/5.3/wp-includes/class-wp-hook.php(288): pmprocc_options_page('')
#1 /wordpress/core/5.3/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/5.3/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /wordpress/core/5.3/wp-admin/admin.php(254): do_action('settings_page_p...')
#4 /wordpress/core/5.3/wp-admin/options-general.php(10): require_once('/wordpress/core...')
#5 {main}
thrown

**Comment by Waleedviews** [comment]
I am facing the same issue, waiting for official comment on this.
